modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"

[[mods]]
modId="usefulspyglass"
version="0.3.0"
displayName="Useful Spyglass"
logoFile="examplemod.png"
credits="BrokenKeyboard"
authors="BrokenKeyboard"
description='''This mod allows players to view information on mobs when viewing them through a spyglass. Also adds spyglass enchantments.'''

[[dependencies.spyglass]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spyglass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"