modLoader="javafml"
loaderVersion="[40,)"
license="GPLv3"

[[mods]]
modId="usefulspyglass"
version="${file.jarVersion}"
displayName="Useful Spyglass"
logoFile="usefulspyglass.png"
credits="BrokenKeyboard"
authors="BrokenKeyboard"
description='''This mod allows players to view information on mobs when viewing them through a spyglass. Also adds spyglass enchantments.'''

[[dependencies.usefulspyglass]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.usefulspyglass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"