modLoader="javafml"
loaderVersion="[40,)"
license="GPL 3.0"

[[mods]]
modId="usefulspyglass"
version="0.3.0"
displayName="Useful Spyglass"
logoFile="examplemod.png"
credits="BrokenKeyboard"
authors="BrokenKeyboard"
description='''This mod allows players to view information on mobs when viewing them through a spyglass. Also adds spyglass enchantments.'''

[[dependencies.spyglass]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spyglass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"